// Package main generates Reset methods for structs marked with // generate:reset.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/packages"
)

const resetDirective = "generate:reset"

type structInfo struct {
	Name    string
	Fields  []fieldInfo
}

type fieldInfo struct {
	Name string
	Type types.Type
}

func main() {
	root, err := findModuleRoot()
	if err != nil {
		fmt.Fprintf(os.Stderr, "module root: %v\n", err)
		fail(1)
	}

	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo,
		Dir:  root,
	}

	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		fmt.Fprintf(os.Stderr, "load packages: %v\n", err)
		fail(1)
	}

	for _, pkg := range pkgs {
		if len(pkg.Errors) > 0 || pkg.Name == "main" && strings.HasSuffix(pkg.PkgPath, "/cmd/reset") {
			continue
		}
		if strings.HasSuffix(pkg.PkgPath, "/cmd/reset") || strings.HasSuffix(pkg.PkgPath, "/cmd/staticlint") {
			continue
		}

		structs := collectStructs(pkg)
		if len(structs) == 0 {
			continue
		}

		content, err := generateFile(pkg.Name, structs, pkg.Types)
		if err != nil {
			fmt.Fprintf(os.Stderr, "generate %s: %v\n", pkg.PkgPath, err)
			fail(1)
		}

		outPath := filepath.Join(filepath.Dir(pkg.GoFiles[0]), "reset.gen.go")
		if err := os.WriteFile(outPath, content, 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "write %s: %v\n", outPath, err)
			fail(1)
		}
	}
}

func fail(code int) {
	os.Exit(code)
}

func findModuleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found")
		}
		dir = parent
	}
}

func collectStructs(pkg *packages.Package) []structInfo {
	var result []structInfo

	for _, file := range pkg.Syntax {
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}

			for _, spec := range gen.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}

				if _, isStruct := typeSpec.Type.(*ast.StructType); !isStruct || !hasResetDirective(gen.Doc, typeSpec.Doc, typeSpec.Comment) {
					continue
				}

				obj := pkg.TypesInfo.Defs[typeSpec.Name]
				named, ok := obj.Type().(*types.Named)
				if !ok {
					continue
				}

				st, ok := named.Underlying().(*types.Struct)
				if !ok {
					continue
				}

				info := structInfo{Name: typeSpec.Name.Name}
				for i := 0; i < st.NumFields(); i++ {
					field := st.Field(i)
					if field.Embedded() {
						continue
					}
					info.Fields = append(info.Fields, fieldInfo{
						Name: field.Name(),
						Type: field.Type(),
					})
				}

				result = append(result, info)
			}
		}
	}

	return result
}

func hasResetDirective(docs ...*ast.CommentGroup) bool {
	for _, doc := range docs {
		if doc == nil {
			continue
		}
		for _, c := range doc.List {
			text := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
			if text == resetDirective || strings.Contains(text, resetDirective) {
				return true
			}
		}
	}
	return false
}

func generateFile(pkgName string, structs []structInfo, pkgTypes *types.Package) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/reset; DO NOT EDIT.\n\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", pkgName))

	for _, st := range structs {
		buf.WriteString(fmt.Sprintf("func (rs *%s) Reset() {\n", st.Name))
		buf.WriteString("\tif rs == nil {\n")
		buf.WriteString("\t\treturn\n")
		buf.WriteString("\t}\n\n")

		for _, field := range st.Fields {
			stmts := resetStatements(field.Name, field.Type, pkgTypes)
			for _, stmt := range stmts {
				buf.WriteString("\t" + stmt + "\n")
			}
		}

		buf.WriteString("}\n\n")
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, err
	}
	return formatted, nil
}

func resetStatements(name string, typ types.Type, pkgTypes *types.Package) []string {
	switch t := typ.Underlying().(type) {
	case *types.Basic:
		return []string{fmt.Sprintf("rs.%s = %s", name, zeroLiteral(t))}
	case *types.Pointer:
		if hasResetMethodOnType(t.Elem(), pkgTypes) {
			return []string{
				fmt.Sprintf("if resetter, ok := rs.%s.(interface{ Reset() }); ok && rs.%s != nil {", name, name),
				"\tresetter.Reset()",
				"}",
			}
		}
		inner := resetPointerTarget(name, t.Elem(), pkgTypes)
		if inner == "" {
			return nil
		}
		return []string{
			fmt.Sprintf("if rs.%s != nil {", name),
			"\t" + inner,
			"}",
		}
	case *types.Slice:
		return []string{fmt.Sprintf("rs.%s = rs.%s[:0]", name, name)}
	case *types.Map:
		return []string{fmt.Sprintf("clear(rs.%s)", name)}
	case *types.Struct:
		if hasResetMethod(t, pkgTypes) {
			return []string{
				fmt.Sprintf("if resetter, ok := any(rs.%s).(interface{ Reset() }); ok {", name),
				"\tresetter.Reset()",
				"}",
			}
		}
		return []string{fmt.Sprintf("rs.%s = %s{}", name, types.TypeString(t, qualifier(pkgTypes)))}
	case *types.Interface:
		return []string{fmt.Sprintf("rs.%s = nil", name)}
	case *types.Array:
		return []string{fmt.Sprintf("rs.%s = %s{}", name, types.TypeString(t, qualifier(pkgTypes)))}
	case *types.Chan:
		return []string{fmt.Sprintf("rs.%s = nil", name)}
	default:
		return []string{fmt.Sprintf("rs.%s = %s{}", name, types.TypeString(typ, qualifier(pkgTypes)))}
	}
}

func resetPointerTarget(name string, elem types.Type, pkgTypes *types.Package) string {
	switch t := elem.Underlying().(type) {
	case *types.Basic:
		return fmt.Sprintf("*rs.%s = %s", name, zeroLiteral(t))
	case *types.Pointer:
		inner := resetPointerTarget(name, t.Elem(), pkgTypes)
		if inner == "" {
			return ""
		}
		return fmt.Sprintf("if rs.%s != nil {\n\t\t%s\n\t}", name, inner)
	case *types.Slice:
		return fmt.Sprintf("*rs.%s = (*rs.%s)[:0]", name, name)
	case *types.Map:
		return fmt.Sprintf("clear(*rs.%s)", name)
	case *types.Struct:
		if hasResetMethod(t, pkgTypes) {
			return fmt.Sprintf("if resetter, ok := any(*rs.%s).(interface{ Reset() }); ok {\n\t\tresetter.Reset()\n\t}", name)
		}
		return fmt.Sprintf("*rs.%s = %s{}", name, types.TypeString(t, qualifier(pkgTypes)))
	case *types.Interface:
		return fmt.Sprintf("*rs.%s = nil", name)
	default:
		return fmt.Sprintf("*rs.%s = %s{}", name, types.TypeString(elem, qualifier(pkgTypes)))
	}
}

func hasResetMethod(st *types.Struct, pkgTypes *types.Package) bool {
	return hasResetMethodOnType(st, pkgTypes)
}

func hasResetMethodOnType(typ types.Type, pkgTypes *types.Package) bool {
	ptr := types.NewPointer(typ)
	obj, _, _ := types.LookupFieldOrMethod(ptr, true, pkgTypes, "Reset")
	fn, ok := obj.(*types.Func)
	return ok && fn.Name() == "Reset"
}

func qualifier(pkg *types.Package) types.Qualifier {
	return func(other *types.Package) string {
		if other == pkg {
			return ""
		}
		return other.Name()
	}
}

func zeroLiteral(b *types.Basic) string {
	switch b.Kind() {
	case types.Bool:
		return "false"
	case types.String, types.UntypedString:
		return `""`
	case types.Int, types.Int8, types.Int16, types.Int32, types.Int64,
		types.Uint, types.Uint8, types.Uint16, types.Uint32, types.Uint64, types.Uintptr,
		types.Float32, types.Float64, types.Complex64, types.Complex128,
		types.UnsafePointer, types.UntypedInt, types.UntypedFloat, types.UntypedComplex:
		return "0"
	default:
		return "0"
	}
}
